// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectAPI.Models;

namespace ProjectAPI.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    partial class ProjectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjectModels.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FName = "Viktor",
                            LName = "Gunnarsson",
                            Titel = "Utvecklare"
                        },
                        new
                        {
                            Id = 2,
                            FName = "Erik",
                            LName = "Norell",
                            Titel = "Utvecklare"
                        },
                        new
                        {
                            Id = 3,
                            FName = "Lukas",
                            LName = "Rose",
                            Titel = "Utvecklare"
                        },
                        new
                        {
                            Id = 4,
                            FName = "Erik",
                            LName = "Risholm",
                            Titel = "Utvecklare"
                        });
                });

            modelBuilder.Entity("ProjectModels.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProjectName = "Desktop Application"
                        },
                        new
                        {
                            Id = 2,
                            ProjectName = "Rest Api"
                        },
                        new
                        {
                            Id = 3,
                            ProjectName = "Mobile Application"
                        },
                        new
                        {
                            Id = 4,
                            ProjectName = "Presentation"
                        });
                });

            modelBuilder.Entity("ProjectModels.TimeReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<double>("HoursWorked")
                        .HasColumnType("float");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ProjectId");

                    b.ToTable("TimeReports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeId = 1,
                            HoursWorked = 40.200000000000003,
                            ProjectId = 1,
                            WeekNumber = 12
                        },
                        new
                        {
                            Id = 2,
                            EmployeeId = 1,
                            HoursWorked = 10.199999999999999,
                            ProjectId = 2,
                            WeekNumber = 12
                        },
                        new
                        {
                            Id = 3,
                            EmployeeId = 3,
                            HoursWorked = 10.5,
                            ProjectId = 3,
                            WeekNumber = 12
                        },
                        new
                        {
                            Id = 4,
                            EmployeeId = 1,
                            HoursWorked = 12.0,
                            ProjectId = 4,
                            WeekNumber = 12
                        },
                        new
                        {
                            Id = 5,
                            EmployeeId = 2,
                            HoursWorked = 40.200000000000003,
                            ProjectId = 2,
                            WeekNumber = 12
                        },
                        new
                        {
                            Id = 6,
                            EmployeeId = 2,
                            HoursWorked = 10.0,
                            ProjectId = 3,
                            WeekNumber = 12
                        },
                        new
                        {
                            Id = 7,
                            EmployeeId = 4,
                            HoursWorked = 45.0,
                            ProjectId = 4,
                            WeekNumber = 12
                        });
                });

            modelBuilder.Entity("ProjectModels.TimeReport", b =>
                {
                    b.HasOne("ProjectModels.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectModels.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
